### ISSUE TITLE
Embed mongo  for easier startup for "playgrounds"... 

### ISSUE THREAD

**Issue by jayunit100** [Megapixel99/nodejs-k8s#2]
# Problem

Getting started requires setting up mongo manually - most K8s folks probably don't have a canned recipe for this... So its a bit of a hurdle... 

# Background

The README mentions... 
```
 33 3. Create an `.env` file and set `DB_URL` to your `MongoDB` instance <---
```

# Solution? 

However, it seems like we could have a docker run command that just bootstrapped mongo right?

**Comment by Megapixel99** [comment]
Yeah, we could add an option to the [startup script](https://github.com/Megapixel99/nodejs-k8s/blob/master/start.sh) that runs a MongoDB instance based on options passed into the CLI

**Comment by Megapixel99** [comment]
Updated the startup script to spin up a MongoDB service.
